name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: AlexanderEllisWilson-Portfolio
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_VERSION: '6.0.x'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: ${{ env.DOTNET_VERSION }}

     - name: Restore
       run: dotnet restore ./AlexPortfolio.sln

     - name: Build
       run: dotnet build ./AlexPortfolio.sln --configuration Release --no-restore
     
     - name: Publish
       run: dotnet publish ./AlexPortfolio.sln --configuration Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

     - name: Deployment
       uses: azure/webapps-deploy@v2
       with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
         package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
