name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '6.0.x'

     - name: Restore
       run: fotnet restore ./AlexPortfolio.sln

     - name: Build
       run: dotnet build ./AlexPortfolio.sln --configuration Release --no-restore
     
     - name: Publish
       run: dotnet publish ./AlexPortfolio.sln --configuration Release --no-build
